services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      - pg_data_volleybolley:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  pg_data_volleybolley:
