services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    volumes:
      - pg_data_volleybolley:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  pg_data_volleybolley:
