# Generated by Django 5.2.1 on 2025-08-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_payment_payment_type_gameinvitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameinvitation',
            options={'verbose_name': 'Game invitation', 'verbose_name_plural': 'Game invitations'},
        ),
        migrations.RemoveConstraint(
            model_name='gameinvitation',
            name='unique following',
        ),
    ]
