# Generated by Django 5.2.1 on 2025-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_gameinvitation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('NOT_DECIDED', 'Not decided')], default='NOT_DECIDED', max_length=30, verbose_name='Invitation status'),
        ),
    ]
