# Generated by Django 5.2.1 on 2025-08-07 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gameinvitation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinvitation',
            name='invited',
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='invited',
            field=models.ManyToManyField(related_name='invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
