from django.utils.translation import gettext_lazy as _

jazzmin_settings = {
    'site_title': _('VolleyBolley Admin'),
    'site_header': _('VolleyBolley'),
    'site_brand': '🏐 VolleyBolley',
    'login_logo_dark': None,
    'welcome_sign': _('Welcome to VolleyBolley Admin Panel'),
    'copyright': 'VolleyBolley 2025',
    'search_model': ['players.Player'],
    'user_avatar': None,
    'topmenu_links': [
        {
            'name': _('🏠 Home'),
            'url': 'admin:index',
            'permissions': ['auth.view_user'],
        },
        {
            'name': _('📊 Dashboard'),
            'url': '/admin/dashboard/',
            'icon': 'fas fa-tachometer-alt',
            'permissions': ['auth.view_user'],
        },
        {
            'name': _('📁 Data Upload'),
            'url': '/admin/data_upload/',
            'permissions': ['auth.change_user'],
        },
        {
            'name': _('📖 API Docs'),
            'url': '/api/swagger/',
            'new_window': True,
        },
    ],
    'usermenu_links': [
        {
            'name': _('👤 Profile'),
            'url': 'admin:auth_user_change',
            'icon': 'fas fa-user',
        },
        {
            'name': _('🔐 Change Password'),
            'url': 'admin:password_change',
            'icon': 'fas fa-key',
        },
        {
            'name': _('🚪 Logout'),
            'url': 'admin:logout',
            'icon': 'fas fa-sign-out-alt',
        },
        {'model': 'auth.user'},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': [],
    'hide_models': [],
    'order_with_respect_to': [
        'courts',
        'event',
        'players',
        'users',
        'courts',
        'locations',
        'core',
    ],
    'icons': {
        'users.user': 'fas fa-user',
        'core.Tag': 'fas fa-tags',
        'core.Contact': 'fas fa-address-book',
        'core.PaymentType': 'fas fa-credit-card',
        'core.Gender': 'fas fa-venus-mars',
        'core.GameLevel': 'fas fa-signal',
        'core.InfoPage': 'fas fa-file-alt',
        'core.FAQ': 'fas fa-question-circle',
        'Core.CurrencyType': 'fas fa-coins',
        'core.InfoSection': 'fas fa-newspaper',
        'core.DailyStats': 'fas fa-bar-chart',
        'locations.Country': 'fas fa-flag',
        'locations.City': 'fas fa-city',
        'notifications.Device': 'fas fa-tablet',
        'notifications.Notificationsbase': 'fas fa-bell',
        'courts.Location': 'fas fa-map-marker-alt',
        'courts.Court': 'fas fa-square',
        'players': 'fas fa-running',
        'players.Player': 'fas fa-volleyball-ball',
        'event.game': 'fas fa-volleyball-ball',
        'event.gameinvitation': 'fas fa-plus',
        'event.tourney': 'fas fa-trophy',
        'tournaments': 'fas fa-medal',
        'tournaments.Tournament': 'fas fa-crown',
        'django_celery_beat.periodictask': 'fas fa-clock',
        'django_celery_beat.clockedschedule': 'fas fa-clock',
        'django_celery_beat.intervalschedule': 'fas fa-stopwatch',
        'django_celery_beat.crontabschedule': 'fas fa-calendar-alt',
        'django_celery_beat.solarschedule': 'fas fa-sun',
        'admin_panel': 'fas fa-cogs',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': False,
    'show_ui_builder': False,
    'changeform_format': 'horizontal_tabs',
    'changeform_format_overrides': {
        'auth.user': 'collapsible',
        'auth.group': 'vertical_tabs',
    },
    'language_chooser': False,
    'site_logo': 'base/site_logo.png',
}

jazzmin_ui_tweaks = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-primary',
    'accent': 'accent-primary',
    'navbar': 'navbar-dark',
    'no_navbar_border': False,
    'navbar_fixed': False,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': False,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': False,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'default',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
    'actions_sticky_top': False,
}
